<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Legacy To Vue</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="build/app.css">
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-68592562-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-68592562-1');
    </script>
</head>
<body>
    <div id="app"></div>
    <script type="text/javascript" src="build/app.js"></script>
</body>
</html>